services:
  ## Session Handling Gate
  countrygate.session_gate:
    class: AaProjects\Countrygate\Service\SessionGate
    arguments:
      - "@request_stack"
    public: true

  ## Form Type Request Token
  countrygate.form.type.request_token:
    class: AaProjects\Countrygate\Form\RequestTokenType
    arguments:
    - "@security.csrf.token_manager"
    - "%contao.csrf_token_name%"
    tags:
    - { name: 'form.type' }
